
import { Inter } from "next/font/google";
import "./globals.css";
import { bungee, fontspring, nunito, poppins , fontspringNormal } from "@/utils/font";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import QRcode from "@/components/QRcode";
import Footerup from "@/components/Footerup";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {



  return (
    <html lang="en" className="scroll-smooth">
      <body className={`bg-[#1A1A1E] relative ${bungee} ${nunito} ${poppins} ${fontspring}  ${fontspringNormal}`}  >
        <Navbar></Navbar>
        {children}
        <QRcode></QRcode>
        {/* <Footer></Footer> */}
        <Footerup></Footerup>

        </body>
    </html>
  );
}
